[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
cfl_program = "7wHZscUp9Zn1uoupNChJybhgU6iDhZ8dof3Phe45n9zU"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "https://rpc.mainnet-alpha.sonic.game"
# cluster = "https://api.testnet.sonic.game/"
cluster = "Localnet"
wallet = "./environment/deployer.json"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"  
program = "tests/metaplex_token_metadata_program.so"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
