[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
cfl_program = "9xqgNAjAWfQdyCvHmBBTsJixpRwEs98ugKLKaA6x9r5w"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "https://rpc.mainnet-alpha.sonic.game"
# cluster = "https://api.testnet.sonic.game/"
# cluster = "Devnet"
# cluster = "http://127.0.0.1:8899"
cluster = "Localnet"
wallet = "./environment/deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
